 
name: Yosys_Test

on:
  push:
    branches:
      - master
    paths:
      - '**/*.*v*'
  pull_request:
   
  workflow_dispatch:

jobs:        
  Yosys_Test:
    runs-on: yosys_runner
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: jitterbit/get-changed-files@v1
        id: abc
        with:
          format: space-delimited
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Look for added and modified files
        run: |
          echo "Added/Modified:"
          echo "${{ steps.abc.outputs.added_modified }}"
          
      - name: Generate run designs file
        run: |
            export CGA_ROOT=$(pwd)
            python3 $CGA_ROOT/.github/gen_filelist.py ${{ steps.abc.outputs.added_modified }}
      
      - name: Synthesizing benchmarks on Yosys
        run: |
         python3 $CGA_ROOT/.github/scripts/tools_auto_scripts/run_cga.py -T yosys -f $CGA_ROOT/run_designs     
 
 
